### ISSUE TITLE
ValueError: Neither [dataset/Amazon/AmazonCloth] exists in the device nor [AmazonCloth] a known dataset name.

### ISSUE THREAD

**Issue by Alpacanm** [Adamli12/CUT_24#3]
ValueError: Neither [dataset/Amazon/AmazonCloth] exists in the device nor [AmazonCloth] a known dataset name.
Where did the dataset used for training this model come from? Displays the name of the dataset and data that does not exist. Can you tell me the relevant information, do you need to do it yourself or is there another way? If you can provide relevant links yourself, thank you very much！

**Comment by Adamli12** [comment]
the link of the dataset is attached in the footnote in the paper
