### ISSUE TITLE
Enquiry about paper details

### ISSUE THREAD

**Issue by WilfridLuo** [Adamli12/CUT_24#4]
Hello Hanyu,

I was re-running your code and would like to ask you further details:

      1. In your paper, the model overview figure shows that you use the transfer mapping F to transfer target user embeddings, however in your code self.target_forward and the transfer function:

self.transform_user(self, user, user_e):  
        if not self.raw_embedding_loss:
            if user != None:
                target_sign = (user < self.target_num_users + 1).unsqueeze(1).float()
                target_users = user_e * target_sign
                nontarget_users = user_e * (1 - target_sign)
                transformed_target_users = torch.mm(target_users,
                                                    self.user_transform_matrix + self.transform_weight * self.user_transform_matrix_r)
                return nontarget_users + transformed_target_users
            else:
                return torch.mm(user_e,
                                self.user_transform_matrix + self.transform_weight * self.user_transform_matrix_r)
        else:
            return user_e
            
      Seems like it will return the input user_e when you call target_forward and the test function. Would you please give more explaination to it?
     
     2. In the original paper, seems like you have some tricks for processing overlap user and it's related parameters theta_o, I didn't find the associated code for optimizing it in your model file cut.py. Would you please give more hints about it? 
     
 Thanks for your help in advance.
 Kind regards,
 Wilfrid

**Comment by Adamli12** [comment]
Thank you for reaching out.

1. the raw_embedding_loss parameter is fixed to 1 in the final version. This parameter determines whether the contrastive loss is calculated based on the raw user embedding or the user representation in the deeper layers of the backbone model. In the paper, we choose the former variation, for better generalization to different backbone models.

2. During the contrastive loss calculation in the BOTH phase, we only consider the target user embeddings. loss_contrastive is derived in lines 631 to 685 in the calculated_loss() function. We can see that it only uses user_id[1]. user_id[1] is defined in line 591, which only contains the target user ids. 

Actually, the user embedding structure of recbole CDR is like this: [overlap user, target other users, source other users]. Therefore we can identify the user's identity given the user index. If you wish to modify the code, this may help.
