### ISSUE TITLE
Implementation of baseline models

### ISSUE THREAD

**Issue by EnkiXin** [Adamli12/CUT_24#5]
Thank you for your interesting research.
I noticed that the results of two baselines in your paper(UniCDR and CAT-ART) used different datasets and experimental setups from their original papers. Could you please provide the code for your implementation of these two papers? Or could you share some details that would help reproduce the comparative experimental results?

**Comment by Adamli12** [comment]
UniCDR has officially released pytorch implementation on github. It can be integerated to RecBole CDR by transferring the model source code and train only the BOTH phase.

CAT-ART on the other hand hasnot released the source code by the publishing date of this paper, so I reimplemented their model following the original paper.

Thank you for asking, but I would recommend you to reach out to the original git repo or author email for more detailed suggestions.
